### ISSUE TITLE
wrapable for a Camunda-Modeler plugin?

### ISSUE THREAD

**Issue by StephenOTT** [bpmn-io/bpmn-js-sketchy#1]
I loooked to wrap this into a modeler plugin, but seems to have a bable issues for the browserify.

Is it possible?

The tests for this package seem to be broken as well.

**Comment by nikku** [comment]
> but seems to have a bable issues for the browserify.

What kind of issues does it _seem to have_?

**Comment by nikku** [comment]
> The tests for this package seem to be broken as well.

This is due to a breaking change introduced in the upstream sketchy rendering toolkit. Fixed via https://github.com/bpmn-io/bpmn-js-sketchy/commit/1a4c9d39bafc85c66e385457de6efc9b652abe81.
