### ISSUE TITLE
provide a Camunda Modeler plugin for this module.

### ISSUE THREAD

**Issue by StephenOTT** [bpmn-io/bpmn-js-sketchy#2]

**Comment by nikku** [comment]
Out of scope for this project. Please open an issue in the relevant project.

Sounds like a good community contribution, by the way :wink:.

**Comment by StephenOTT** [comment]
@nikku i gave it a quick try, but there seems to be issues with babelify/browserify transpile of the SketchyRenderer.js file `..ParseError: 'import' and 'export' may appear only with 'sourceType: module...`
