### ISSUE TITLE
Sketchy renderer direction of arrow missing about sequence flow element

### ISSUE THREAD

**Issue by lienide** [bpmn-io/bpmn-js-sketchy#3]
### Describe the Bug
Same header...

### Steps to Reproduce

1. check out master branch and v0.6.0
2. npm i & npm run dev
3. open browser and then click debug model
4. show pic as below:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/29501807/230329830-81ea90fa-da6e-4054-9a99-b9d3ad8003fe.png">

### Expected Behavior

is possible with direction in hand draw diagram?

### Environment

- Host safari
- OS: mac
- Library version: master & v0.6.0tag

**Comment by nikku** [comment]
I can reproduce your issue.

**Comment by nikku** [comment]
Fixed with `v0.7.0`.
